#1132 Migrate to IntelliJ Platform Gradle Plugin 2.0
google/google-java-format pull request #1134
Opened 2024-08-14 06:11 UTC by mmaeller

Hello,

I have no experience in IntelliJ plugin development, but maybe I can support you that the required invest in time isn't that high. As far as I can tell the `gradle build` works.

Due to the changes of the IntelliJ gradle plugin I was urged to raise the java compatibility to 17 as well as the supported IntelliJ version to at least 2022.3 (see [requirements](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html#requirements))

#1132

2024-08-16 02:20 UTC, plumpy requested changes
Thanks, I appreciate the help!

We can't merge it until you sign the CLA, so if you could do that, it would be great!

2024-08-16 02:20 UTC, plumpy commented on idea_plugin/build.gradle.kts
> +val googleJavaFormatVersion = "1.23.0"
let's save this upgrade for a different commit... there are a few other things that need to change with a version upgrade (like the release notes), so let's just keep this PR for the build configuration changes.

2024-08-19 19:17 UTC, plumpy commented
Hi, could you head over to https://cla.developers.google.com/ to sign the CLA?

2024-08-20 07:44 UTC, mmaeller commented
> Hi, could you head over to https://cla.developers.google.com/ to sign the CLA?

Hi @plumpy,

I signed it twice: primary and secondary email addresses of the account.
As far as I see the built-in checks have been successfully passed :)

2024-08-21 14:56 UTC, closed without merging